// Package spec embeds the OpenAPI/Swagger 2.0 spec generated by `swag init`.
// Regenerate with `just openapi`. The bytes are served at /openapi.json and
// also fed into internal/toolspec for OpenAI/Anthropic tool-schema conversion.
package spec

import _ "embed"

//go:embed swagger.json
var Swagger []byte
